# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.06.115620'

RELEASE_GIT_HEAD = '47e28ad0a3c6f0a82ad1199fab336e0dd6670481'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
